server.port=8080
spring.data.mongodb.uri=mongodb+srv://tabbaraabed4_db_user:ZTX9QcYm0DbzUdlO@cluster0.vun1s40.mongodb.net/caltrack?retryWrites=true&w=majority
spring.data.mongodb.database=caltrack
spring.jackson.serialization.write-dates-as-timestamps=false
